### ISSUE TITLE
cannot use the "usePayload" hook on fastify-vite-vue

### ISSUE THREAD

**Issue by davidmeirlevy** [fastify/fastify-dx#10]
on the the previous version, i use the `usePayload` as described in the docs:

```ts
import {usePayload} from 'fastify-vite-vue/core';

export default {
  components: {},
  setup() {
    const myData = usePayload()
    /// doing something..
    return {myData}
  }
}
```

on the new version I tried to import `usePayload` from both: `fastify-vite-vue/blueprint/entry/core` and `/entry/core`

both returned the same error:

ℹ     at render (/my-app/node_modules/fastify-vite-vue/render.js:7:13)
ℹ     at Object.<anonymous> (/my-app/node_modules/fastify-vite/mode/development.js:72:24)
ℹ     at preHandlerCallback (/my-app/node_modules/fastify/lib/handleRequest.js:126:28)
ℹ     at next (/my-app/node_modules/fastify/lib/hooks.js:158:7)
ℹ     at handleResolve (/my-appnode_modules/fastify/lib/hooks.js:175:5)
ℹ     at processTicksAndRejections (node:internal/process/task_queues:96:5)

is there a new way to use the payload behavior now?

**Comment by galvez** [comment]
This is fixed in the Fastify DX for Vue (wrapping up!), closing this as it pertains to an outdated API.
