### ISSUE TITLE
Add support for x-vhost HTTP header

### ISSUE THREAD

**Issue by micheleriva** [fastify/fastify-dx#2]
**Is your feature request related to a problem? Please describe.**
There are cases where it is not possible to edit the `host` file (i.e., CI phase), but still, the multi-tenancy layer needs to work. 

**Describe the solution you'd like**
Given the following `app.mjs` content:

```js
export const tenants = {
  foo: 'foo.dev',
  bar: 'bar.dev',
}
```

it would be handy to configure a `x-vhost` HTTP header which will tell universify which tenant we want to reach:

```bash
curl -H "x-vhost: foo.dev" -X GET http://localhost:3000
```

Testing frameworks such as Cypress already support the possibility to add custom HTTP headers to their test calls.

**Comment by galvez** [comment]
Closing this until we revisit multi-tenant support.
