### ISSUE TITLE
Need to define a common configuration layer

### ISSUE THREAD

**Issue by micheleriva** [fastify/fastify-dx#3]
**Is your feature request related to a problem? Please describe.**
One common problem when working with multi-tenant applications is that they might need a strong configuration layer containing information to be used at build time (i.e., when statically generating a webapp), or at runtime (i.e. endpoints, third-party plugin configurations, etc.).

It would be useful to propose a standard way to manage configurations for every tenant.

**Describe the solution you'd like**
In [Krabs](https://github.com/micheleriva/krabs#examples), we used to put all the configuration inside a `.krabs.js` file in the project's root:

```js
module.exports = async () => ({
  tenants: [
    {
      name: 'website-1',
      // add any property here
      domains: [
        {
          development: /dev\.[a-z]*\.local\.website-1\.com/,
          staging: 'stage.website-1.com',
          production: 'website-1.com',
        },
      ],
    },
    {
      name: 'website-2',
      // add any property here
      domains: [
        {
          development: 'local.website-2.com',
          staging: 'stage.website-2.com',
          production: /[\w|\d|-|_]+\.website-2.com/,
        },
      ],
    },
  ],
});
```

It is important that the configurations can be retrieved asynchronously, as they can come from different data sources (CMSs, e-commerce platforms, etc.) and depend on the current environment (stage, dev, prod, test).

I'm not sure this is the right way to proceed in Universify, I'm open to discussions!

**Comment by galvez** [comment]
Closing this until we revisit multi-tenant support.
