### ISSUE TITLE
Add support for environment-based domains

### ISSUE THREAD

**Issue by micheleriva** [fastify/fastify-dx#4]
**Is your feature request related to a problem? Please describe.**
Domains can depend on the current environment. For example, when developing `example.com`, we might have the following domains:

- Production: `example.com`
- Staging: `fix-JIRA-126300-somefix.user.staging.example.com`
- Development: `local.example.com`

**Describe the solution you'd like**
I'd propose to change the tenants configuration in `app.mjs` from this:

```js
export const tenants = {
  foo: 'foo.dev',
  bar: 'bar.dev',
}
```

into something like this:

```js
export const tenants = {
  foo: {
    dev: 'local.foo.dev',
    stage: /[\w]+\.foo\.dev/,
    prod: 'foo.dev'
  },
  // ...
}
```

Typically, the right domain gets selected by the `NODE_ENV` environment variable. Still, I find it quite repetitive to maintain hundreds of domains by hand-writing them in the format above, so I'm open to discussing a better solution!

This issue links to #3, as domains could depend on the configuration layer.

**Comment by galvez** [comment]
Closing this until we revisit multi-tenant support.
